### ISSUE TITLE
How to decompose a mask when processing images with CNNs?

### ISSUE THREAD

**Issue by skyday123** [AndyShih12/mac#1]
I like this work, but I don't understand the decomposition protocol when it comes to images, particularly with rotation/flip data augmentations. How to define the "greatest element $j$" here? ($w\text{-MAC}_e(j)=1$)

**Comment by AndyShih12** [comment]
The "greatset element" is w.r.t. some global canonical ordering (say 1,2,3,....100 counting left-to-right top-to-down). That is done in this line [here](https://github.com/AndyShih12/mac/blob/84a63e53ccbc0b605f83bc67616bce7395a4047d/image_model.py#L128), where the sort operation puts the pixels in the canonical order.

You would treat an augmented image as a separate new image (i.e. forget that it was a rotation of another image), and still use the same canonical ordering.

**Comment by skyday123** [comment]
Thanks for your response!
